services:
  embeddings:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embeddings
    ports:
      - '50001:50001'
    environment:
      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY
      - HF_AUTH_TOKEN
      - ROOT
      - DEVICE
      - BATCH_SIZE
      - ADDITIONAL_SPEAKERS
      - API_URL
      - MAX_QUEUE_SIZE
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]

volumes:
  hugging_face_cache:
